import requests
import json
import openai
import os
import logging
import datetime
from dotenv import load_dotenv

load_dotenv()


class RepoAnalyzer:
    """Agent for generating and reviewing PlantUML diagrams from code."""

    def __init__(self, openai_api_key, url):
        self.openai_api_key = openai_api_key
        self.openai_base_url = url
        self.headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {self.openai_api_key}'
        }

    def generate_puml(self, repo):
        """Generate PlantUML from method description."""
        data = {
            "model": "gpt-3.5-turbo",
            "messages": [
                {
                    "role": "user",
                    "content": "I need to translate the given method content into a detailed .puml by logic, so not in the style of a class diagram but in a style that a non technical person could understand what's going on. The output should be compatible with https://plantuml.com/, meaning you will not confuse it with mermaid syntax."
                },
                {
                    "role": "system",
                    "content": "Understood! Please provide the detailed content of the method."
                },
                {
                    "role": "user",
                    "content": f"Method: {repo}"
                }
            ]
        }

        response = requests.post(self.openai_base_url, headers=self.headers, json=data)
        puml_content = response.json()["choices"][0]["message"]["content"]
        return puml_content

    def review_and_correct_puml(self, puml_content):
        """Review and correct PlantUML syntax."""
        example_puml = """@startuml
title Data Processing Workflow
skinparam Activity {
  BackgroundColor PaleGreen
  BorderColor DarkGreen
}
start
partition UserInput {
    :Receive user request;
    :Validate input parameters;
}
partition DataProcessing {
    :Load data from storage;
    if (data valid?) then (yes)
        :Process data;
        :Store results;
    else (no)
        :Log error;
        :Return error message;
        stop
    endif
}
:Return success response;
stop
@enduml"""

        data = {
            "model": "gpt-4",
            "messages": [
                {
                    "role": "user",
                    "content": "The following is a .puml content generated by an agent. Please critically review it and correct any mistakes, especially ensuring it strictly adheres to .puml syntax and does not contain any elements from other diagramming languages like Mermaid."
                },
                {
                    "role": "system",
                    "content": f"Understood! As I'm an expert in the .puml syntax like the following: '{example_puml}', I will be able to distinguish the right from the wrong and correct wrong syntax. Please provide the .puml content to review."
                },
                {
                    "role": "user",
                    "content": puml_content
                }
            ]
        }

        response = requests.post(self.openai_base_url, headers=self.headers, json=data)
        corrected_puml_content = response.json()["choices"][0]["message"]["content"]
        return corrected_puml_content


if __name__ == "__main__":
    openai_api_key = os.getenv('OPENAI_API_KEY')
    open_ai_url = "https://api.openai.com/v1/chat/completions"
    bot = RepoAnalyzer(openai_api_key, open_ai_url)

    method_desc = """
    def apply_rows(self, table_id, schema, rows):
        try:
            if not self._table_exists(table_id):
                self._create_table(table_id, schema)
                print(f"Inserting rows to {table_id}: {rows}")
            self._insert_rows(table_id, rows)
            self.logger.info(f"apply_rows {table_id} o.k")
        except Exception as e:
            error_msg = f'apply_rows encountered the Error: {str(e)}'
            self.logger.error(error_msg)
            raise Exception(e)
    """

    puml_content = bot.generate_puml(method_desc)
    print(puml_content)
